"""empty message

Revision ID: 5ed66fc6634b
Revises: adfe0fb3cae5
Create Date: 2025-02-04 21:25:28.969019

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ed66fc6634b"
down_revision = "adfe0fb3cae5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("birthday", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("telephone", sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column("github", sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ["github"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("github")
        batch_op.drop_column("telephone")
        batch_op.drop_column("birthday")

    # ### end Alembic commands ###
