"""empty message

Revision ID: 8ad4e2504d70
Revises: a681d144e97a
Create Date: 2025-02-04 23:08:02.087229

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ad4e2504d70"
down_revision = "a681d144e97a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dailies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint("dailies_team_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.drop_column("team_user_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dailies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("team_user_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "dailies_team_user_id_fkey", "team_users", ["team_user_id"], ["id"]
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
