"""empty message

Revision ID: a681d144e97a
Revises: adab625c52a7
Create Date: 2025-02-04 23:02:38.190697

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a681d144e97a"
down_revision = "adab625c52a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "telephone",
            existing_type=sa.VARCHAR(length=11),
            type_=sa.String(length=13),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "telephone",
            existing_type=sa.String(length=13),
            type_=sa.VARCHAR(length=11),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
