"""empty message

Revision ID: adab625c52a7
Revises: f9c45aface94
Create Date: 2025-02-04 21:56:08.049666

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "adab625c52a7"
down_revision = "f9c45aface94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scholarship_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "scholarships", ["scholarship_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("scholarship_id")

    # ### end Alembic commands ###
